/**
 *
 * @author April Nickel
 */
public enum ScreenOption {
    MAIN_MENU,
    USER_SELECT, USER_VIEW, USER_NEW,
    DIARY_MENU, DIARY_VIEW, DIARY_NEW_ENTRY,
    ACTIVITY_MENU, ACTIVITY_LOG_VIEW, ACTIVITY_NEW,
    EXIT_CONFIRM, EXIT
}
